# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.letta_schemas_message_message_output import LettaSchemasMessageMessageOutput
from .agents_list_messages_response_item import AgentsListMessagesResponseItem

AgentsListMessagesResponse = typing.Union[
    typing.List[LettaSchemasMessageMessageOutput], typing.List[AgentsListMessagesResponseItem]
]
