# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.system_message_output import SystemMessageOutput
from ...types.user_message_output import UserMessageOutput
from ...types.internal_monologue import InternalMonologue
from ...types.function_call_message import FunctionCallMessage
from ...types.function_return import FunctionReturn
from ...types.assistant_message_output import AssistantMessageOutput
from ...types.letta_usage_statistics import LettaUsageStatistics

LettaStreamingResponse = typing.Union[
    SystemMessageOutput,
    UserMessageOutput,
    InternalMonologue,
    FunctionCallMessage,
    FunctionReturn,
    AssistantMessageOutput,
    LettaUsageStatistics,
]
