# This file was auto-generated by Fern from our API Definition.

import typing

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingRequireOutputMapping = (
    typing.Union[bool, typing.Optional[typing.Any]]
)
