# This file was auto-generated by Fern from our API Definition.

import typing

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemOneType = typing.Union[
    typing.Literal["InitToolRule"],
    typing.Literal["TerminalToolRule"],
    typing.Literal["continue_loop"],
    typing.Literal["conditional"],
    typing.Literal["ToolRule"],
    typing.Literal["require_parent_tools"],
    typing.Optional[typing.Any],
]
