# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
from .templates_create_agents_from_template_response_agents_item_tool_rules_item_item_item_child_output_mapping_type import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingType,
)
from .templates_create_agents_from_template_response_agents_item_tool_rules_item_item_item_child_output_mapping_default_child import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChild,
)
from .templates_create_agents_from_template_response_agents_item_tool_rules_item_item_item_child_output_mapping_require_output_mapping import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingRequireOutputMapping,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMapping(UncheckedBaseModel):
    tool_name: str
    type: typing.Optional[
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingType
    ] = None
    default_child: typing.Optional[
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChild
    ] = None
    child_output_mapping: typing.Optional[typing.Optional[typing.Any]] = None
    require_output_mapping: typing.Optional[
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingRequireOutputMapping
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
