# This file was auto-generated by Fern from our API Definition.

import typing
from .templates_create_agents_from_template_response_agents_item_tool_rules_item_item_item_child_output_mapping_default_child_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChildItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChild = typing.Union[
    str,
    typing.Optional[str],
    typing.List[
        typing.Optional[
            TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChildItem
        ]
    ],
    typing.Optional[typing.Any],
]
