# This file was auto-generated by Fern from our API Definition.

import typing

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemItemChildOutputMappingDefaultChildItem = (
    typing.Union[str, typing.Optional[str]]
)
