configured_endpoints: 117
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/letta-ai%2Fletta-sdk-4e14f08c6f1c6bc43d4ade3d273ed496dcd340f54f94f5186bfae7855bfc41d2.yml
openapi_spec_hash: 68cc3920d034bba6b9e1ccfc34ec42f7
config_hash: 679cc6b0aae84dcf2facfb0ed1151c0f
