configured_endpoints: 139
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/letta-ai%2Fletta-sdk-26ab5ad4e1be375fbc8958f99caaa919228797dbea2eefedce4d5be34452e742.yml
openapi_spec_hash: fdcb01a2647a18019fcb1ef99a6cbb9a
config_hash: f0a4efea53972b995311bbcf3f2aeec2
