# This file was auto-generated by Fern from our API Definition.

import typing
from ....types.message_create import MessageCreate
from ....types.message_input import MessageInput

LettaStreamingRequestMessages = typing.Union[typing.List[MessageCreate], typing.List[MessageInput]]
