# This file was auto-generated by Fern from our API Definition.

import typing
from ....types.letta_schemas_message_message_output import LettaSchemasMessageMessageOutput
from .messages_list_response_item import MessagesListResponseItem

MessagesListResponse = typing.Union[
    typing.List[LettaSchemasMessageMessageOutput], typing.List[MessagesListResponseItem]
]
