# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, TypeAlias

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = [
    "MessageCreateResponse",
    "AssistantMessage",
    "FunctionCall",
    "FunctionCallDelta",
    "FunctionCallMessage",
    "FunctionCallMessageFunctionCall",
    "FunctionCallMessageFunctionCallFunctionCall",
    "FunctionCallMessageFunctionCallFunctionCallDelta",
    "FunctionReturn",
    "InternalMonologue",
    "LettaUsageStatistics",
    "SystemMessage",
    "UserMessage",
]


class AssistantMessage(BaseModel):
    id: str

    assistant_message: str

    date: datetime

    message_type: Optional[Literal["assistant_message"]] = None


class FunctionCall(BaseModel):
    arguments: str

    function_call_id: str

    name: str


class FunctionCallDelta(BaseModel):
    arguments: Optional[str] = None

    function_call_id: Optional[str] = None

    name: Optional[str] = None


class FunctionCallMessageFunctionCallFunctionCall(BaseModel):
    arguments: str

    function_call_id: str

    name: str


class FunctionCallMessageFunctionCallFunctionCallDelta(BaseModel):
    arguments: Optional[str] = None

    function_call_id: Optional[str] = None

    name: Optional[str] = None


FunctionCallMessageFunctionCall: TypeAlias = Union[
    FunctionCallMessageFunctionCallFunctionCall, FunctionCallMessageFunctionCallFunctionCallDelta
]


class FunctionCallMessage(BaseModel):
    id: str

    date: datetime

    function_call: FunctionCallMessageFunctionCall

    message_type: Optional[Literal["function_call"]] = None


class FunctionReturn(BaseModel):
    id: str

    date: datetime

    function_call_id: str

    function_return: str

    status: Literal["success", "error"]

    message_type: Optional[Literal["function_return"]] = None

    stderr: Optional[List[str]] = None

    stdout: Optional[List[str]] = None


class InternalMonologue(BaseModel):
    id: str

    date: datetime

    internal_monologue: str

    message_type: Optional[Literal["internal_monologue"]] = None


class LettaUsageStatistics(BaseModel):
    completion_tokens: Optional[int] = None
    """The number of tokens generated by the agent."""

    prompt_tokens: Optional[int] = None
    """The number of tokens in the prompt."""

    step_count: Optional[int] = None
    """The number of steps taken by the agent."""

    total_tokens: Optional[int] = None
    """The total number of tokens processed by the agent."""


class SystemMessage(BaseModel):
    id: str

    date: datetime

    message: str

    message_type: Optional[Literal["system_message"]] = None


class UserMessage(BaseModel):
    id: str

    date: datetime

    message: str

    message_type: Optional[Literal["user_message"]] = None


class MessageCreateResponse(BaseModel):
    assistant_message: Optional[AssistantMessage] = FieldInfo(alias="AssistantMessage", default=None)

    function_call: Optional[FunctionCall] = FieldInfo(alias="FunctionCall", default=None)

    function_call_delta: Optional[FunctionCallDelta] = FieldInfo(alias="FunctionCallDelta", default=None)

    function_call_message: Optional[FunctionCallMessage] = FieldInfo(alias="FunctionCallMessage", default=None)
    """
    A message representing a request to call a function (generated by the LLM to
    trigger function execution).

    Attributes: function_call (Union[FunctionCall, FunctionCallDelta]): The function
    call id (str): The ID of the message date (datetime): The date the message was
    created in ISO format
    """

    function_return: Optional[FunctionReturn] = FieldInfo(alias="FunctionReturn", default=None)
    """
    A message representing the return value of a function call (generated by Letta
    executing the requested function).

    Attributes: function_return (str): The return value of the function status
    (Literal["success", "error"]): The status of the function call id (str): The ID
    of the message date (datetime): The date the message was created in ISO format
    function_call_id (str): A unique identifier for the function call that generated
    this message stdout (Optional[List(str)]): Captured stdout (e.g. prints, logs)
    from the function invocation stderr (Optional[List(str)]): Captured stderr from
    the function invocation
    """

    internal_monologue: Optional[InternalMonologue] = FieldInfo(alias="InternalMonologue", default=None)
    """Representation of an agent's internal monologue.

    Attributes: internal_monologue (str): The internal monologue of the agent id
    (str): The ID of the message date (datetime): The date the message was created
    in ISO format
    """

    letta_usage_statistics: Optional[LettaUsageStatistics] = FieldInfo(alias="LettaUsageStatistics", default=None)
    """Usage statistics for the agent interaction.

    Attributes: completion_tokens (int): The number of tokens generated by the
    agent. prompt_tokens (int): The number of tokens in the prompt. total_tokens
    (int): The total number of tokens processed by the agent. step_count (int): The
    number of steps taken by the agent.
    """

    system_message: Optional[SystemMessage] = FieldInfo(alias="SystemMessage", default=None)
    """A message generated by the system.

    Never streamed back on a response, only used for cursor pagination.

    Attributes: message (str): The message sent by the system id (str): The ID of
    the message date (datetime): The date the message was created in ISO format
    """

    user_message: Optional[UserMessage] = FieldInfo(alias="UserMessage", default=None)
    """A message sent by the user.

    Never streamed back on a response, only used for cursor pagination.

    Attributes: message (str): The message sent by the user id (str): The ID of the
    message date (datetime): The date the message was created in ISO format
    """
