# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Optional
from typing_extensions import Required, Annotated, TypedDict

from .._utils import PropertyInfo

__all__ = ["ToolCreateParams"]


class ToolCreateParams(TypedDict, total=False):
    source_code: Required[str]
    """The source code of the function."""

    update: bool

    id: Optional[str]
    """The unique identifier of the tool.

    If this is not provided, it will be autogenerated.
    """

    description: Optional[str]
    """The description of the tool."""

    json_schema: Optional[object]
    """
    The JSON schema of the function (auto-generated from source_code if not
    provided)
    """

    module: Optional[str]
    """The module of the function."""

    name: Optional[str]
    """The name of the function (auto-generated from source_code if not provided)."""

    source_type: Optional[str]
    """The type of the source code."""

    tags: List[str]
    """Metadata tags."""

    terminal: Optional[bool]
    """Whether the tool is a terminal tool (allow requesting heartbeats)."""

    body_user_id: Annotated[Optional[str], PropertyInfo(alias="user_id")]
    """The unique identifier of the user associated with the function."""

    header_user_id: Annotated[str, PropertyInfo(alias="user_id")]
