# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal

from ..._models import BaseModel

__all__ = [
    "MessageCreateResponse",
    "MessagesUnionMember0",
    "MessagesUnionMember0ToolCall",
    "MessagesUnionMember0ToolCallFunction",
    "MessagesUnionMember1",
    "Usage",
]


class MessagesUnionMember0ToolCallFunction(BaseModel):
    arguments: str
    """The arguments to pass to the function (JSON dump)"""

    name: str
    """The name of the function to call"""


class MessagesUnionMember0ToolCall(BaseModel):
    id: str
    """The ID of the tool call"""

    function: MessagesUnionMember0ToolCallFunction
    """The arguments and name for the function"""

    type: Optional[str] = None


class MessagesUnionMember0(BaseModel):
    role: Literal["assistant", "user", "tool", "function", "system"]
    """The role of the participant."""

    id: Optional[str] = None
    """The human-friendly ID of the Message"""

    agent_id: Optional[str] = None
    """The unique identifier of the agent."""

    created_at: Optional[datetime] = None
    """The time the message was created."""

    model: Optional[str] = None
    """The model used to make the function call."""

    name: Optional[str] = None
    """The name of the participant."""

    text: Optional[str] = None
    """The text of the message."""

    tool_call_id: Optional[str] = None
    """The id of the tool call."""

    tool_calls: Optional[List[MessagesUnionMember0ToolCall]] = None
    """The list of tool calls requested."""

    user_id: Optional[str] = None
    """The unique identifier of the user."""


class MessagesUnionMember1(BaseModel):
    id: str

    date: datetime


class Usage(BaseModel):
    completion_tokens: Optional[int] = None
    """The number of tokens generated by the agent."""

    prompt_tokens: Optional[int] = None
    """The number of tokens in the prompt."""

    step_count: Optional[int] = None
    """The number of steps taken by the agent."""

    total_tokens: Optional[int] = None
    """The total number of tokens processed by the agent."""


class MessageCreateResponse(BaseModel):
    messages: Union[List[MessagesUnionMember0], List[MessagesUnionMember1]]
    """The messages returned by the agent."""

    usage: Usage
    """The usage statistics of the agent."""
