# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateThreadRequest(UniversalBaseModel):
    messages: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of message IDs associated with the thread.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Metadata associated with the thread.
    """

    assistant_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the assistant (i.e. Letta preset)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
