# This file was auto-generated by Fern from our API Definition.

import typing
from .letta_schemas_letta_message_function_call import LettaSchemasLettaMessageFunctionCall
from .function_call_delta import FunctionCallDelta

FunctionCallMessageFunctionCall = typing.Union[LettaSchemasLettaMessageFunctionCall, FunctionCallDelta]
