# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .function import Function
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class LettaSchemasOpenaiOpenaiToolCall(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique identifier of the tool call.
    """

    type: typing.Optional[str] = None
    function: Function = pydantic.Field()
    """
    The function call.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
