# This file was auto-generated by Fern from our API Definition.

import typing
from .open_ai_tool_calls_step import OpenAiToolCallsStep
from .open_ai_message_creation_step import OpenAiMessageCreationStep

OpenAiRunStepStepDefaults = typing.Union[OpenAiToolCallsStep, OpenAiMessageCreationStep]
