# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .open_ai_message_content_item import OpenAiMessageContentItem
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class OpenAiMessage(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique identifier of the message.
    """

    object: typing.Optional[str] = None
    created_at: int = pydantic.Field()
    """
    The unix timestamp of when the message was created.
    """

    thread_id: str = pydantic.Field()
    """
    The unique identifier of the thread.
    """

    role: str = pydantic.Field()
    """
    Role of the message sender (either 'user' or 'system')
    """

    content: typing.Optional[typing.List[OpenAiMessageContentItem]] = pydantic.Field(default=None)
    """
    The message content to be processed by the agent.
    """

    assistant_id: str = pydantic.Field()
    """
    The unique identifier of the assistant.
    """

    run_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the run.
    """

    file_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of file IDs associated with the message.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Metadata associated with the message.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
