# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .letta_schemas_openai_openai_tool_call import LettaSchemasOpenaiOpenaiToolCall
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class OpenAiToolCallsStep(UniversalBaseModel):
    type: typing.Optional[str] = None
    tool_calls: typing.List[LettaSchemasOpenaiOpenaiToolCall] = pydantic.Field()
    """
    The tool calls.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
