# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class OpenAiUsage(UniversalBaseModel):
    completion_tokens: int = pydantic.Field()
    """
    The number of tokens used for the run.
    """

    prompt_tokens: int = pydantic.Field()
    """
    The number of tokens used for the prompt.
    """

    total_tokens: int = pydantic.Field()
    """
    The total number of tokens used for the run.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
